# name -> (resolved_address, place_id, f0_note)   [session f00a0b22 turn 39, verbatim; HTML entities unescaped]
A2RES = {
"Noma":("Refshalevej 96, 1432 København","ChIJpYCQZztTUkYRFOE368Xs6kI","Listed by White Guide at Global Masters; absent from MICHELIN 2026 Copenhagen. A2 catching what A1 drops."),
"Studio":("Paulas Passage 5, 1799 København","ChIJFW375DxTUkYRXjq0HuABUN4","Places name 'Restaurant STUDIO'."),
"Bistro Boheme":("Esplanaden 8, 1263 København","ChIJK4QsYh9TUkYRf8_-L5qs8r0",""),
"Connection":("Øster Farimagsgade 18, 2100 København","ChIJ21nHWfdTUkYRVQblxRLUcdA","Places name 'Connection by Alan Bates'."),
"Démodé":("Kronprinsessegade 64, 1306 København","ChIJ-Us_W4VTUkYRpMZcOfPrGaU",""),
"Esmée":("Kongens Nytorv 8, 1050 København","ChIJe-VmuYBTUkYRZw3JVGZxcrQ","Shares Kongens Nytorv 8 with Goldfinch — distinct venues, one address."),
"Grim":("Ryesgade 65A, 2100 København","ChIJjRiU4pBTUkYRzv0uiC2AlxU","Source gives locality 'Köpenhamn'. Shares Ryesgade 65 with Tèrra — distinct venues, adjacent numbers."),
"La Banchina":("Refshalevej 141, 1432 København","ChIJe2R04ddSUkYRPspah4LjBEs",""),
"Lumskebugten":("Esplanaden 21, 1263 København","ChIJ930z5iBTUkYRdgKM4AvI9KE",""),
"Schønnemann":("Hauser Pl. 16, 1127 København","ChIJx2QJkxpTUkYR0MR2kI3TJlo",""),
"Trio":("Axel Towers, Jernbanegade 11, 1609 København","ChIJL6pGyQ1TUkYR_bGHKmWisCw","Places name 'Trio Restaurant & Bar'."),
"ÅBEN":("Slagtehusgade 15, 1715 København","ChIJu2MtLi1TUkYRX5UmSXRahyk","Places name 'ÅBEN Kødbyen'; classified as brewpub/bar as well as restaurant."),
"Alf":("Gl. Kongevej 86A, 1850 Frederiksberg","ChIJ-7iMbc1TUkYR066Hz1SQ-EI",""),
"Ambra":("Store Kongensgade 59, 1264 København","ChIJn9SA1ORTUkYRAzw2Mr7JRiY",""),
"Apéro":("Gammel Mønt 41, 1117 København","ChIJo55UwFtTUkYRa3wddVc97hM",""),
"Baka d'Busk":("Rantzausgade 44, 2200 København","ChIJrRrd1AxTUkYRCAM2kLImW_o",""),
"Bar La Una":("Oehlenschlægersgade 53A, 1663 København","ChIJb68b_sNTUkYRE-H3ITU1Nxw",""),
"Bar Moro":("Blegdamsvej 36, 2200 København","ChIJeZNuTchTUkYRGsyJ4J8jywM",""),
"Barabba":("Store Kongensgade 34, 1264 København","ChIJ2W1BWxhTUkYRdPRopYGyxSc",""),
"Boutique Emilia":("Frederiksholms Kanal 4, kl.th, 1220 København","ChIJabtByUVTUkYRgiNlxHfBJJ0",""),
"Brasserie Post":("Øster Allé 1, 2100 København","ChIJfYJzl_tSUkYRFfCJfwa56CQ","F0 NAME MISMATCH: guide 'Brasserie Post', Places 'POST Spisehus'. Same address; treated as one venue."),
"Brus":("Guldbergsgade 29, 2200 København","ChIJN-5GHkeLS0YRUMSC1_FNNAE","Shares Guldbergsgade 29 with Bæst and Mirabelle — three distinct listings at one address."),
"Café Sommersko":("Palægade 6, 1260 København","ChIJo2pWYs5TUkYRJFWe1fgaib8","Guide gives Palægade 2-6."),
"Cleo":("Rantzausgade 58B, 2200 København","ChIJ7ze9DX9TUkYRvWdzxtad290",""),
"Damindra":("Sankt Annæ Pl. 16, 1250 København","ChIJWQdyJD1TUkYRlowZ5N1SJys","ADDRESS CONFLICT: guide gives Holbergsgade 26, Places gives Sankt Annæ Plads 16. Both Københavns Kommune, so F1 unaffected. Possible relocation — operator check."),
"Donda SOLÈNE":("Århusgade 1, 2100 København","ChIJj_PMBslTUkYRxSW3lnj1_24","Places name 'SOLÈNE'. Shares Århusgade 1 with Brasserie Barner."),
"Fojetta":("Borups Allé 112, 2000 Frederiksberg","ChIJ2z0jYQBTUkYRIIRdiTTEvK8",""),
"Goldfinch":("Kongens Nytorv 8, st tv, 1050 København","ChIJOXgo1OZTUkYRvgK52A2018A",""),
"Hos Fischer":("Victor Borges Pl. 12, 2100 København","ChIJ79nhzvpSUkYRMdWgdsInJ1w",""),
"Hummer":("Nyhavn 63A, 1051 København","ChIJ9-1l0zxTUkYR6CxC34DbBz0",""),
"JUJU":("Øster Farimagsgade 8, 2100 København","ChIJx6D9Hy1TUkYRNx8YdmTjxSg","Places name 'Juju'."),
"Lago":("Korsgade 1, 2200 København","ChIJ_bpAbkpTUkYR9TBMMLV7I1I",""),
"Lamar":("Gl. Kongevej 27, 1610 København","ChIJD_SV6tFTUkYRMqh0UVudY3w",""),
"Le Saint Jacques":("Sankt Jakobs Pl. 1, 2100 København","ChIJ7QXNffpSUkYR3ywk1ZoPf14",""),
"Locale 21":("Ny Østergade 21, 1101 København","ChIJ_2i8u4pTUkYRqy3P-U7wHqI",""),
"Maison":("Dronningens Tværgade 43, 1302 København","ChIJ-Sw5dpxTUkYR1iQernmhu1k","Places name 'Restaurant Maison'."),
"Margo":("Vesterbrogade 38, 1., 1620 København","ChIJTa2jHQBTUkYRoq1YEpcI8g4",""),
"Mirabelle":("Guldbergsgade 29, 2200 København","ChIJ2QDM_apTUkYRvlCBYFjWh48","Places name 'Mirabelle Cph'. Shares address with Bæst and Brus."),
"Nr. 30":("Nansensgade 30, 1366 København","ChIJwx8gswhTUkYR5EfyAr9voys","Places name 'Nr.30 Spisested & Vinbar'."),
"Oberra":("Skjolds Pl. 2, 4, 2200 København","ChIJ5yxNk-5TUkYRjmkkXhocIYM",""),
"Pauli":("Borgbjergsvej 13, 2450 København","ChIJu_enbD1TUkYR5EmpspnWBx8",""),
"Piola Pastificio":("Thorvaldsensvej 2c, 1871 Frederiksberg","ChIJa3XoD3tTUkYR2EyPuQVc4uM",""),
"Pirlo Vinbar":("Strandlodsvej 42a, 2300 København","ChIJd3ytQWitU0YRhvRfLCVTinM","Places name 'Pirlo Vin | Osteria | Bar'."),
"Propaganda - next door":("Vester Farimagsgade 2, 1606 København","ChIJh-Gb9_RTUkYRIL8ctdYUIa8","Places lists parent 'Propaganda'. Guide lists the 'next door' concept specifically — operator should confirm these are one venue or two."),
"Resto Bar":("Vesterbrogade 51, 1620 København","ChIJIVPhCvRTUkYR4p3mrqgKl7M","Rendered twice within Very Fine tier at source; one venue."),
"Ripotot":("Store Kongensgade 56, 1264 København","ChIJpcOaOx1TUkYR-dn4NEsyTtc",""),
"SURT":("Bag Elefanterne 2, 1799 København","ChIJD5I7D95TUkYR3gs-GWlVWlI",""),
"Silo":("Helsinkigade 29, 17. sal, 2150 København","ChIJC8r_LOpSUkYR4YyY79-1OjI","Places name 'Restaurant Silo'."),
"Tèrra":("Ryesgade 65, 2100 København","ChIJIXKV5_1SUkYRIeSqukUEPbc","Shares Ryesgade 65 with Grim."),
"Brasserie Barner":("Århusgade 1, 2100 København","ChIJ7w8U5fBSUkYRs8_NCF6G4Hg","Shares Århusgade 1 with Donda SOLÈNE."),
"Bæst":("Guldbergsgade 29, 2200 København","ChIJfXsI359TUkYRXn0Fbeq4Uy0","Shares address with Mirabelle and Brus."),
"Delphine":("Vesterbrogade 40, 1620 København","ChIJC5QC73BTUkYRmGgAmkKtMKs",""),
"Donda Deli":("Dybbølsgade 52, 1721 København","ChIJH8j6JPZTUkYR0_5fw0DRbAY","F0 NAME MISMATCH: guide 'Donda Deli', Places 'DONDA'. Same address; treated as one venue."),
"Gaarden & Gaden":("Nørrebrogade 88, 2200 København","ChIJv_-9gatTUkYRaaBerWme7RI",""),
"Le Lac":("Classensgade 11A, 2100 København","ChIJp8eohUFTUkYRLeupwNIi0bw",""),
"Ma Cuisine":("Ravnsborggade 19, 2200 København","ChIJ1-eGn_9TUkYRcaX0m9s1Dtk",""),
"Noels":("Sigurdsgade 39, 2200 København","ChIJB_uvUZ1TUkYRfRw7hm-crlk","Places name 'NOELS Restaurant & Vinbar'; connected to a nightclub per reviews."),
"Noi":("H. C. Andersens Blvd. 34, 1574 København","ChIJ__9PEhNTUkYRUueDYXvDHUw","ADDRESS CONFLICT: guide gives Niels Brocks Gade 1, Places gives H.C. Andersens Blvd 34 — corner site, likely the same building. Both Københavns Kommune."),
"Odette":("Kompagnistræde 18, 1208 København","ChIJm-zUNHtTUkYRBylv5V0gg8o","Places name 'Restaurant Odette'."),
"Safari":("Baggesensgade 9, 2200 København","ChIJCyzLwt1TUkYRtJ0gDnMyW1o",""),
"Seaside Toldboden":("Nordre Toldbod 18-24, 1259 København","ChIJi53zoiBTUkYRWRzV-Ll4NBM","Multi-kitchen food-hall format per its own description — F2 and price will not behave like a single restaurant."),
"Told & Snaps":("Toldbodgade 2, 1253 København","ChIJwbaX1CJTUkYR-PzHUAibjmo",""),
"Masseria":("Flæsketorvet 50, 1711 København","ChIJU9kJAlRTUkYRwz2geBucZaE","F0 NAME MISMATCH: guide 'Masseria', Places 'Tavola Di Masseria'. Same address; treated as one venue."),
"Royal Garden":("Dronningens Tværgade 30, 1302 København","ChIJ8xDP4hhTUkYRwxp5B1KQ7wU",""),
"Kappo Ando":("Øster Farimagsgade 93, 2100 København","ChIJiWs_L6VTUkYRS2njduWvzZA","SAME VENUE AS A1 'Aotori' (D-035). White Guide uses the name 'Kappo Ando', MICHELIN's slug is kappo-ando but its display name is Aotori. One venue, three names."),
}
UNRESOLVED = {
"Kiin Kiin Tok Tok":"F0 UNRESOLVED: guide gives Vesterbrogade 55; Places returns 'Kiin Kiin Bao Bao' at Vesterbrogade 96 — different name AND different address. Not accepted as a match.",
"Toto":"F0 UNRESOLVED: guide gives Amagerbrogade 145; Places returns 'Restaurant Il Gambero Rosso' at Amagerbrogade 166-168 — a different restaurant. Not accepted as a match.",
"[NAME MISSING AT SOURCE]":"F0 UNRESOLVED: source renders no venue name; address occupies the name field. Malmö address — outside boundary regardless.",
}
