# resolution map: name -> (address, place_id)
# Transcribed from session f00a0b22 turn 27 (/home/claude/resolution_map.py), HTML entities unescaped.
RES = {
"Geranium":("Per Henrik Lings Allé 4, 8. Sal, 2100 København","ChIJAQshwflSUkYRF9f4wpDIt7U"),
"Kadeau Copenhagen":("Wildersgade 10B, 1408 København","ChIJ1Y52MZlTUkYRuDl4FNhYh_U"),
"Jordnær":("Gentoftegade 29, 2820 Gentofte","ChIJWxyiJPFNUkYRTp10-YnYcNg"),
"Kong Hans Kælder":("Vingårdstræde 6, 1070 København","ChIJXdbkpBdTUkYRO6NpiMExk-w"),
"Alchemist":("Refshalevej 173C, 1432 København","ChIJGbFWVvBSUkYR5x0i6Z836Ao"),
"Koan":("Langeliniekaj 5, 2100 København","ChIJoxbQhIBTUkYR15NWp69nCt0"),
"a|o|c":("Dronningens Tværgade 2, 1302 København","ChIJM6fyhhhTUkYRy5Y4y78NEYU"),
"formel B":("Vesterbrogade 184, 1800 Frederiksberg","ChIJtxaAuZlTUkYRt9S0ULtIiuA"),
"Udtryk":("Teglgårdstræde 8A, 1452 København","ChIJn1w7Q6ZTUkYRHVs90CYuMPg"),
"Marchal":("Hotel d'Angleterre, Kongens Nytorv 34, 1050 København","ChIJtRm9KRhTUkYRhIT68DTO0r8"),
"Lille Mølle":("Christianshavns Voldgade 52, st, 1424 København","ChIJ29LGogVTUkYRcswK32qPzAY"),
"akmē":("Sandkaj 39, 2150 København","ChIJ97znST9TUkYRXKSLIQ5ezzc"),
"Aure":("Krudtløbsvej 8, 1439 København","ChIJV_8E0sJTUkYRRlJfxBk5d6k"),
"Sushi Anaba":("Mariehamngade 23, 2150 København","ChIJc7_JfGlTUkYRbVK5FOovyOs"),
"Alouette":("Kronprinsessegade 8, 1306 København","ChIJcXrr90dTUkYRNJo6gjI26uk"),
"texture":("Sølvgade 86, 1307 København","ChIJRxVkAFJTUkYRGaQE2cWK7fU"),
"Jatak":("Rantzausgade 39, 2200 København","ChIJu7H8HXxTUkYRuLKQbQU824w"),
"ESSE":("Trelleborggade 13a, 2100 København","ChIJZ7egZwBTUkYRAQ5WQBRR2nM"),
"Parsley Salon":("Strandvejen 203, 2900 Hellerup","ChIJhTbZQNNTUkYRrlURja_vdgM"),
"The Samuel":("Hellerupvej 40, 2900 Hellerup","ChIJ97nnHBpTUkYRtJSEQUisX6o"),
"Søllerød Kro":("Søllerødvej 35, 2840 Søllerød","ChIJua9HeudOUkYRDn953dEtd1Y"),
"Uformel":("Studiestræde 69, 1554 København","ChIJSe-tLwxTUkYRMfme3amPWPI"),
"Radio":("Julius Thomsens Gade 12, 1632 København","ChIJd6nGjadTUkYR_uqnU-UHNIU"),
"Norrlyst":("Kompagnistræde 8, 1208 København","ChIJKZN-gpVTUkYRZIA81TOgWQ0"),
"Botschaft":("Ryesgade 25, 2200 København","ChIJu2Qrd_pTUkYRdaGe0ym5180"),
"Bobe":("Gråbrødretorv 11, 1154 København","ChIJZ_VYz2VTUkYRRmm8b7HNGaY"),
"Gabrielle":("Vestergade 3, 1456 København","ChIJiUJH2NJTUkYRHAjn5YaXLAA"),
"Abigail & Co":("Nørregade 30, 1165 København","ChIJ3RsX_XdTUkYRFYi4Z_R5U3c"),
"Restaurant Glassalen":("Vesterbrogade 3, 1620 København","ChIJeRv4oyFTUkYRG9vfeA9nSHE"),
"Sankt Annæ":("Sankt Annæ Pl. 12, 1250 København","ChIJhWmN6SJTUkYRKlpUjxJ0eWk"),
"Aamanns 1921":("Niels Hemmingsens Gade 19, 21, 1153 København","ChIJoa1vixBTUkYRD8NYW74jRsc"),
"Theo":("Skindergade 29, 1159 København","ChIJ_fVFwHJTUkYRxc_S43Xw8b4"),
"Restaurant Palægade":("Palægade 8, 1261 København","ChIJMUS-QxhTUkYROwdtv2vfFwQ"),
"Restaurant Kanalen":("Wilders Pl. 2, 1403 København","ChIJL8NdbTxTUkYR-bra61KbZcc"),
"Mark":("Axeltorv 3, 1609 København","ChIJ5Qw1Eo9TUkYRDcfi4Qhax3U"),
"Petra Bar & Restaurant":("Dronningens Tværgade 45, 1302 København","ChIJ0Uu25mBTUkYR9yLg_mzJs1I"),
"Restaurant Frank":("Grønnegade 33, 1107 København","ChIJkZpy0xlTUkYRcypj3SGxtgQ"),
"Sanchez":("Istedgade 60, 1658 København","ChIJSybl9nRTUkYRDTUvZhSgv5k"),
"no.2":("Nicolai Eigtveds Gade 32, 1402 København","ChIJg_vhKz5TUkYR7GN5bOpKpHI"),
"Enomania":("Vesterbrogade 187, 1800 Frederiksberg","ChIJYw9uaJdTUkYRsOa9paHwFU0"),
"Silberbauers Bistro":("Jægersborggade 40, 2200 København","ChIJYX5oGcJTUkYRMEjS3-IeMBk"),
"Rebel":("Store Kongensgade 52, 1264 København","ChIJp96W7RhTUkYRN1oYKEENdjQ"),
"Pluto":("Borgergade 16, 1300 København","ChIJnRZCABlTUkYRdbR4fra9eNQ"),
"Anarki":("Vodroffsvej 47, 1900 Frederiksberg","ChIJxbhE5wlTUkYR_7gCKTivwqs"),
"Marv & Ben":("Snaregade 4, 1205 København","ChIJjZNJOBFTUkYRXsKrS_T8jPY"),
"Mêlée":("Martensens Allé 16, 1828 Frederiksberg","ChIJsc96MKJTUkYRtgsRhPo3Zvw"),
"Graziano":("Møllegade 13, 2200 København","ChIJ-afUl1pTUkYRPtUAc4pkAKk"),
"Selma":("Rømersgade 20, 1362 København","ChIJ4R8rop9TUkYRmvDmmb-gVOw"),
"Calma":("Jægersborggade 34, 2200 København","ChIJBaNmBoJTUkYRrsaRZR-yjgw"),
"Bistro Lupa":("Marstalsgade 8, 2100 København","ChIJs0sknTtTUkYRp4JWLJtE6iU"),
"Koefoed":("Landgreven 3, 1301 København","ChIJSUn9UxhTUkYRYd5e3r3hbYY"),
"Paesàno":("Jægersborggade 41, kl, 2200 København","ChIJqxBDTOtTUkYRyApMyChMNoA"),
"Levi":("Ny Østergade 24, 1101 København","ChIJOyGohitTUkYRWv3PpzYnh7w"),
"Fasangården":("Søndre Fasanvej 73, 2000 Frederiksberg","ChIJZ3CctrNTUkYR_r2fhzO8Qgo"),
"Restaurant Anton":("Store Strandstræde 3, 1255 København","ChIJmem1rURTUkYRQoaLTrtNF9g"),
"Ark":("Nørre Farimagsgade 63, 1364 København","ChIJA_-cUgRTUkYR2S4zKT6ne94"),
"Kødbyens Fiskebar":("Flæsketorvet 100, 1711 København","ChIJ6a9VvnNTUkYR70EJ8UFFlv0"),
"Høst":("Nørre Farimagsgade 41, 1364 København","ChIJRQ8L7QVTUkYRVW6qA8zFQpg"),
"Barr":("Strandgade 93, 1401 København","ChIJpYCQZztTUkYRb2QOlnW8vvE"),
"The Pescatarian":("Amaliegade 49, 1256 København","ChIJG0wuOUlTUkYRNkeP030CboA"),
"Kiin Kiin VeVe":("Dampfærgevej 7, 2100 København","ChIJi4qvSedSUkYR2yXSzlt_sEM"),
"Aotori":("Øster Farimagsgade 93, 2100 København","ChIJiWs_L6VTUkYRS2njduWvzZA"),
"Kiin Kiin":("Guldbergsgade 21, 2200 København","ChIJSRTl7WNTUkYRJXpAtSgMeVo"),
"Møntergade":("Møntergade 19, 1120 København","ChIJnd0AwJVTUkYRrFyxfFwuEYw"),
"Krogs Fiskerestaurant":("Gammel Strand 38, 1202 København","ChIJ4VOX0hZTUkYRPrHTyGp1LmI"),
"Magny":("Ny Adelgade 3, 1104 København","ChIJP0ubtI1TUkYR7hN2eqZ0OYY"),
"à terre":("Tordenskjoldsgade 11, 1055 København","ChIJ-fk2NRBTUkYRyhj40xrfESA"),
"Amalie":("Amaliegade 11, 1256 København","ChIJ2zHfWCJTUkYRtwCsk6_J7YA"),
"Vækst":("Sankt Peders Stræde 34, 1453 København","ChIJvY9hWg5TUkYRZiYvRZFtDyU"),
"Admiralgade 26":("Admiralgade 26, 1066 København","ChIJaf5c-RZTUkYROL7MbAnhjrA"),
"Mielcke & Hurtigkarl":("Frederiksberg Runddel 1, 2000 Frederiksberg","ChIJvXWLfb1TUkYRyupc-CtZRsA"),
"Restaurant VIE":("Århusgade 128E, 2150 København","ChIJR4W9ZABTUkYRwo3H0nwNzn8"),
}

F0_NOTES = {
"Abigail & Co":"F0: guide name 'Abigail & Co'; Places returns 'Restaurant Abigail'. Same address, treated as one venue.",
"Kiin Kiin VeVe":"F0: guide name 'Kiin Kiin VeVe'; Places returns 'Veve'. Same address, treated as one venue.",
"Aotori":"F0: guide URL slug is 'kappo-ando', display name 'Aotori'; Places returns 'Aotori / Akaton' — two concepts at one address. Needs an operator decision before collection.",
"Marchal":"venue_type = hotel_restaurant (Hotel d'Angleterre). Qualifies on A1 in its own right per D-028.",
"formel B":"Guide labels 'Copenhagen'; address is Frederiksberg Kommune. In scope, but not for the reason the label implies.",
"Restaurant VIE":"Guide files under locality 'Nordhavn'; address 2150 København = Københavns Kommune. A city-label filter would have wrongly excluded this venue.",
}
